apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-app-deployment
  labels:
    app: jokes-app
spec:
  selector:
    matchLabels:
      app: jokes-app
  template:
    metadata:
      labels:
        app: jokes-app
    spec:
      containers:
        - name: jokes-app
          image: europe-north1-docker.pkg.dev/weighty-sunbeam-442221-j2/docker-images/jokes-app:latest
          ports:
            - containerPort: 7777
          resources:
            requests: 
              cpu: "250m"
              memory: "500Mi"
            limits: 
              cpu: "250m"
              memory: "500Mi"