version: "3.9"

services:
  todo-api:
    build: 
      context: todo-api
      dockerfile: Dockerfile.prod
    image: todo-api-prod
    restart: "on-failure"
    volumes:
      - ./todo-api:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - database-migrations
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-api
    ports:
      - 7800:7800

  database:
    container_name: postgresql_database
    image: postgres:16.1
    restart: unless-stopped
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file:
      - project.env
    restart: unless-stopped
    ports:
      - "8888:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - pgadmin

  database-migrations:
    image: flyway/flyway:10.17.3-alpine
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  todo-ui:
    build: 
      context: todo-ui
      dockerfile: Dockerfile.prod
    image: todo-ui-prod
    restart: "on-failure"
    ports:
      - 3000:80
    depends_on:
      - todo-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

volumes:
  pg_data:
  astro_node_modules:
  pgadmin_data: