version: "3.4"

services:
  redis-api:
    build: redis-api
    image: redis-api
    restart: "no"
    volumes:
      - ./redis-api:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - database-migrations
      - redis
    env_file:
      - project.env
    deploy:
        replicas: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis-api
    ports:
      - 7800:7800

  database:
    container_name: postgresql_database
    image: postgres:16.1
    restart: "no"
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  database-migrations:
    image: flyway/flyway:10.17.3-alpine
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  app-astro:
    build: app-astro
    image: app-astro
    restart: "no"
    volumes:
      - ./app-astro/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - redis-api

volumes:
  pg_data:
  astro_node_modules: