services:
  todo-api:
    build: todo-api
    image: todo-api
    restart: "no"
    volumes:
      - ./todo-api:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777-7778:7777
    depends_on:
      - database
      - database-migrations
    env_file:
      - project.env
    deploy:
        replicas: 2

  database:
    container_name: postgresql_database
    image: postgres:16.1
    restart: "no"
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  database-migrations:
    image: flyway/flyway:10.17.3-alpine
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

volumes:
  pg_data: