apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config

data:
  nginx.conf: |
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      proxy_cache_path /var/cache/nginx keys_zone=astro_ssg_cache:1m inactive=5m max_size=512m;

      upstream qa-api {
        server qa-api:7777;
      }

      upstream qa-ui {
        server qa-ui:3000;
      }

      server {
        listen 7800;

        location /api/ {
          proxy_pass http://qa-api/;
          add_header Cache-Control 'no-store';
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }

        location / {
          proxy_pass http://qa-ui;
          proxy_cache astro_ssg_cache;
          proxy_cache_key $uri;
          proxy_cache_valid 5m;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }
      }
    }
